<a href="https://colab.research.google.com/github/darshitp091/patel_darshit_data_science_bytexl_tp/blob/main/NumberCruncher.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv("/StudentsPerformance.csv")

In [4]:
math_all   = df["math score"].values.astype(float)
read_all   = df["reading score"].values.astype(float)
write_all  = df["writing score"].values.astype(float)

In [5]:
print("=" * 60)
print("TASK 1 – NumPy Array of 50 score")
print("=" * 60)

TASK 1 – NumPy Array of 50 Scores


In [6]:
score = math_all[:50]
random_score = np.random.randint(0, 100, size=50)

In [8]:
print(f"Real score (first 50 math): {score}")
print(f"Random score (np.random):     {random_score}")

Real scores (first 50 math): [72. 69. 90. 47. 76. 71. 88. 40. 64. 38. 58. 40. 65. 78. 50. 69. 88. 18.
 46. 54. 66. 65. 44. 69. 74. 73. 69. 67. 70. 62. 69. 63. 56. 40. 97. 81.
 74. 50. 75. 57. 55. 58. 53. 59. 50. 65. 55. 66. 57. 82.]
Random scores (np.random):     [95 35  6 24 87 21 80 17 15 56  0 52 90 78 45 93 54  4 79 83 15 22 54 80
  2 71  7 67 43  6 46 34 60 74 64 10 39  0 38 57 91 24 98 31 89 89 80 80
 25 23]


In [9]:
print("\n" + "=" * 60)
print("TASK 2 – Descriptive Statistics")
print("=" * 60)


TASK 2 – Descriptive Statistics


In [11]:
mean_score   = np.mean(score)
median_score = np.median(score)
std_score    = np.std(score)
highest      = np.max(score)
lowest       = np.min(score)
p25          = np.percentile(score, 25)
p75          = np.percentile(score, 75)

In [12]:
print(f"  Mean    : {mean_score:.2f}")
print(f"  Median  : {median_score:.2f}")
print(f"  Std Dev : {std_score:.2f}")
print(f"  Highest : {highest}")
print(f"  Lowest  : {lowest}")
print(f"  25th %ile: {p25}")
print(f"  75th %ile: {p75}")

  Mean    : 62.84
  Median  : 65.00
  Std Dev : 15.01
  Highest : 97.0
  Lowest  : 18.0
  25th %ile: 54.25
  75th %ile: 71.75


In [13]:
print("\n" + "=" * 60)
print("TASK 3 – Boolean Masking: Fails & Distinctions")
print("=" * 60)


TASK 3 – Boolean Masking: Fails & Distinctions


In [14]:
fail_mask        = score < 40
distinction_mask = score > 85

In [15]:
fail_mask        = score < 40
distinction_mask = score > 85

In [16]:
fail_score        = score[fail_mask]
distinction_score = score[distinction_mask]

In [17]:
fail_indices        = np.where(fail_mask)[0]
distinction_indices = np.where(distinction_mask)[0]

In [18]:
print(f"  Fail score (<40)       : {fail_score}")
print(f"  Fail student indices    : {fail_indices}")
print(f"  Total failures          : {len(fail_score)}")
print()
print(f"  Distinction score (>85): {distinction_score}")
print(f"  Distinction indices     : {distinction_indices}")
print(f"  Total distinctions      : {len(distinction_score)}")

  Fail score (<40)       : [38. 18.]
  Fail student indices    : [ 9 17]
  Total failures          : 2

  Distinction score (>85): [90. 88. 88. 97.]
  Distinction indices     : [ 2  6 16 34]
  Total distinctions      : 4


In [19]:
print("\n" + "=" * 60)
print("TASK 4 – Normalize score  [0, 1]")
print("=" * 60)


TASK 4 – Normalize score  [0, 1]


In [20]:
normalized = (score - score.min()) / (score.max() - score.min())

In [21]:
print(f"  Original   : {score}")
print(f"  Normalized : {np.round(normalized, 3)}")
print(f"  Min after norm: {normalized.min():.4f}  (should be 0.0)")
print(f"  Max after norm: {normalized.max():.4f}  (should be 1.0)")

  Original   : [72. 69. 90. 47. 76. 71. 88. 40. 64. 38. 58. 40. 65. 78. 50. 69. 88. 18.
 46. 54. 66. 65. 44. 69. 74. 73. 69. 67. 70. 62. 69. 63. 56. 40. 97. 81.
 74. 50. 75. 57. 55. 58. 53. 59. 50. 65. 55. 66. 57. 82.]
  Normalized : [0.684 0.646 0.911 0.367 0.734 0.671 0.886 0.278 0.582 0.253 0.506 0.278
 0.595 0.759 0.405 0.646 0.886 0.    0.354 0.456 0.608 0.595 0.329 0.646
 0.709 0.696 0.646 0.62  0.658 0.557 0.646 0.57  0.481 0.278 1.    0.797
 0.709 0.405 0.722 0.494 0.468 0.506 0.443 0.519 0.405 0.595 0.468 0.608
 0.494 0.81 ]
  Min after norm: 0.0000  (should be 0.0)
  Max after norm: 1.0000  (should be 1.0)


In [22]:
print("\n" + "=" * 60)
print("TASK 5 – Reshape  5 subjects × 10 students")
print("=" * 60)


TASK 5 – Reshape  5 subjects × 10 students


In [23]:
 matrix = score.reshape(5, 10)
 row_averages = np.mean(matrix, axis=1)
col_averages = np.mean(matrix, axis=0)

In [24]:
subject_labels = ["Math", "Reading", "Writing", "Science", "Social"]

In [25]:
print("  Score Matrix (5 × 10):")
print(matrix)
print()
print("  Row-wise averages (per subject):")
for label, avg in zip(subject_labels, row_averages):
    print(f"    {label:10s}: {avg:.2f}")
print()
print(f"  Col-wise averages (per student 1-10): {np.round(col_averages, 2)}")

  Score Matrix (5 × 10):
[[72. 69. 90. 47. 76. 71. 88. 40. 64. 38.]
 [58. 40. 65. 78. 50. 69. 88. 18. 46. 54.]
 [66. 65. 44. 69. 74. 73. 69. 67. 70. 62.]
 [69. 63. 56. 40. 97. 81. 74. 50. 75. 57.]
 [55. 58. 53. 59. 50. 65. 55. 66. 57. 82.]]

  Row-wise averages (per subject):
    Math      : 65.50
    Reading   : 56.60
    Writing   : 65.90
    Science   : 66.20
    Social    : 60.00

  Col-wise averages (per student 1-10): [64.  59.  61.6 58.6 69.4 71.8 74.8 48.2 62.4 58.6]
